/*
 * generated by Xtext
 */
package org.example.entities.validation

import org.eclipse.xtext.validation.Check
import org.example.entities.entities.Entity
import org.example.entities.entities.EntitiesPackage
import org.example.entities.entities.Attribute

/**
 * Custom validation rules. 
 *
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
class EntitiesValidator extends AbstractEntitiesValidator
{
  public static val ms_DUBIOUS_ENTITY_NAME = 'org.example.entities.DubiousEntityName'
  public static val ms_DUBIOUS_ATTRIBUTE_NAME = 'org.example.entities.DubiousAttributeName'
  public static val ms_CIRCULAR_ENTITY_HIERARCHY = 'org.example.entities.CircularEntityHierarchy'

	@Check
	def checkEntityStartsWithCapital(Entity entity)
	{
    //System.out.println("Check to see if 1st letter of the Entity '" + entity.name + "' is upper case")

		if (!Character.isUpperCase(entity.name.charAt(0)))
		{
			warning(
			  'An entity should start with a capital letter!', 
			  EntitiesPackage.eINSTANCE.entity_Name,
			  ms_DUBIOUS_ENTITY_NAME, entity.name
			)
		}
	}

  @Check
  def checkAttributeStartsWithLowerCase(Attribute attr)
  {
    //System.out.println("Check to see if 1st letter of the Attribute '" + attr.name + "' is lower case")

    if (!Character.isLowerCase(attr.name.charAt(0)))
    {
      warning(
        'An attribute name should start with a lower-case letter!', 
        EntitiesPackage.eINSTANCE.attribute_Name,
        ms_DUBIOUS_ATTRIBUTE_NAME, attr.name
      )
    }
  }

  @Check
  def checkNoCycleInEntityHierarchy(Entity entity)
  {
    //System.out.println("Check for Circular Extends for '" + entity.name + "'")

    val visitedEntities = <Entity>newHashSet()
    visitedEntities += entity
    var curEntity = entity.superType
    var child = entity
    while (curEntity != null)
    {
      if (visitedEntities.contains(curEntity))
      {
        error(
          "When extending an entity there cannot be a circular reference from '" +
           child.name + "' back to '" + curEntity.name + "'!",
          EntitiesPackage.eINSTANCE.entity_SuperType,
          ms_CIRCULAR_ENTITY_HIERARCHY, child.name, curEntity.name
        )
        return
      }

      visitedEntities += curEntity
      child = curEntity
      curEntity = curEntity.superType
    }
  }
}
